In [2]:
#from pydoc import cli

import numpy as np
#import incoming as inc
import matplotlib.pyplot as plt
import pandas as pd
from alpaca.data.historical import StockHistoricalDataClient, OptionHistoricalDataClient
from alpaca.data.requests import StockBarsRequest, StockQuotesRequest, OptionTradesRequest, OptionBarsRequest, OptionLatestQuoteRequest
OptionBarsRequest
from alpaca.data.timeframe import TimeFrame ; import cudf as cdf 
from datetime import datetime, timezone, date
import polars as pl
from alpaca.data.live import StockDataStream, OptionDataStream
from account import API_KEY , API_SECRET
from collections import  deque
import pyqtgraph as pg 


global  t2

199636.66

In [7]:
# alpaca_data_client.py


class AlpacaDataClient:
    def __init__(self, api_key: str, api_secret: str):
        self.stock_hist = StockHistoricalDataClient(api_key, api_secret)
        self.option_hist = OptionHistoricalDataClient(api_key, api_secret)

        self.stock_stream = StockDataStream(api_key, api_secret)
        self.option_stream = OptionDataStream(api_key, api_secret)

    # =========================
    # HISTORICAL — STOCKS
    # =========================
    def stock_bars(self, symbols, timeframe, start=None, end=None, limit=None):
        req = StockBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_bars(req)

    def stock_trades(self, symbols, timeframe, start=None, end=None, limit=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,

            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_trades(req)

    def stock_quotes(self, symbols, start=None, end=None
, limit=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_quotes(req)

    # =========================
    # HISTORICAL — OPTIONS
    # =========================
    def option_bars(self, symbols, timeframe, start=None, end=None, limit=None):
        req = OptionBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_bars(req)

    def option_trades(self, symbols, start=None, end=None, limit=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_trades(req)

    def option_quotes(self, symbols, start=None, end=None, limit=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_latest_quote(req)

    # =========================
    # STREAMING — STOCKS
    # =========================
    def stream_stock_bars(self, symbols, handler):
        self.stock_stream.subscribe_bars(handler, *symbols)

    def stream_stock_trades(self, symbols, handler):
        self.stock_stream.subscribe_trades(handler, *symbols)

    def stream_stock_quotes(self, symbols, handler):
        self.stock_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # STREAMING — OPTIONS
    # =========================
    def stream_option_trades(self, symbols, handler):
        self.option_stream.subscribe_trades(handler, *symbols)

    def stream_option_quotes(self, symbols, handler):
        self.option_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # RUN STREAMS
    # =========================
    async def run_stock_stream(self):
        await self.stock_stream.run()

    async def run_option_stream(self):
        await self.option_stream.run()

In [3]:

yymmdd = date.today().strftime("%y%m%d")  # "260204"
yymmdd

'260219'

Calls

ReQuests

In [8]:
list = ["SYM", "INTC", "NVDA", "ARM", "AMD"]
start_date = datetime(2026,2, 10)
end_date = datetime.now()
list[0]

def MakeOptionsym(sym:str, type: str, date : datetime, strike):
    date =  date.strftime("%y%m%d")

    strike = int(round(strike * 1000))

    pad = 8 - len(str(strike))
    pad = str(0).zfill(pad)
    i = sym+str(date)+type+str(pad)+str(strike)
    return i

z = MakeOptionsym(list[1],"C",datetime(2026,1,30), 75)
print(z)

INTC260130C00075000

In [9]:
client  = AlpacaDataClient(API_KEY, API_SECRET) 
#S_Quotes = client.stock_quotes(symbols=list[0],   start=start_date, end=datetime.now()).df
S_Bars = client.stock_bars(symbols=list[0],timeframe=TimeFrame.Minute, start=start_date, end=datetime.today()).df
#S_Trades = client.stock_trades(symbols=list[0],timeframe=TimeFrame.Hour,start=datetime(2026, 1, 30), end=datetime.today()).df
# remeber old time and call
#  and new time and add the data frame btw those times

In [10]:
S_Bars = S_Bars.reset_index()
S_Bars

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,SYM,2026-02-10 00:32:00+00:00,63.15,63.15,63.15,63.15,100.0,1.0,63.15
1,SYM,2026-02-10 00:36:00+00:00,62.80,62.80,62.80,62.80,556.0,1.0,62.80
2,SYM,2026-02-10 00:41:00+00:00,62.80,62.80,62.80,62.80,572.0,2.0,62.80
3,SYM,2026-02-10 00:55:00+00:00,62.80,62.80,62.80,62.80,238.0,4.0,62.80
4,SYM,2026-02-10 09:14:00+00:00,62.86,62.86,62.86,62.86,325.0,12.0,62.86
...,...,...,...,...,...,...,...,...,...
2487,SYM,2026-02-19 09:53:00+00:00,54.99,54.99,54.99,54.99,314.0,21.0,54.99
2488,SYM,2026-02-19 10:12:00+00:00,55.00,55.00,55.00,55.00,632.0,7.0,55.00
2489,SYM,2026-02-19 10:16:00+00:00,54.93,54.93,54.93,54.93,280.0,8.0,54.93
2490,SYM,2026-02-19 10:28:00+00:00,54.98,54.98,54.98,54.98,300.0,2.0,54.98
2491,SYM,2026-02-19 10:48:00+00:00,54.89,54.89,54.89,54.89,422.0,4.0,54.89

In [ ]:

tradeCount = S_Bars['trade_count']
vwap = S_Bars['vwap']

x = np.asarray(tradeCount)
y = np.asarray(vwap)
n = np.gradient(x, y)

print(n)

[  -0.                   nan           nan ... -384.28571429 -242.22222222
  -22.22222222]

/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1290: RuntimeWarning: divide by zero encountered in divide
  a = -(dx2)/(dx1 * (dx1 + dx2))
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1290: RuntimeWarning: invalid value encountered in divide
  a = -(dx2)/(dx1 * (dx1 + dx2))
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1291: RuntimeWarning: divide by zero encountered in divide
  b = (dx2 - dx1) / (dx1 * dx2)
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1291: RuntimeWarning: invalid value encountered in divide
  b = (dx2 - dx1) / (dx1 * dx2)
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1292: RuntimeWarning: divide by zero encountered in divide
  c = dx1 / (dx2 * (dx1 + dx2))
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1292: RuntimeWarning: invalid value encountered in divide
  c = dx1 / (dx2 * (dx1 + dx2))
/home/nvitop/.conda/envs/rapids-25.12/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:1298: RuntimeWarning: invalid value encountered in add
  out[tuple(slice1)] = a * f[tuple(slice2)] + b * f[tuple(slice3)] + c * f[tuple(slice4)]

In [ ]:
mk = pg.mkQApp()
win = pg.PlotWidget()
p1 = win.plot(n)

mk.exec()

In [ ]:

#Options 
#O_Quotes = client.option_quotes(z, start=start_date, end=datetime.today())
O_Bars = client.option_bars(z,timeframe=TimeFrame.Hour,start= start_date, end=datetime.today())
O_Trades = client.option_trades(z, start=start_date, end=datetime.today())

In [ ]:
import time
from datetime import datetime

# purpose was to update data each frame 

t2 = datetime.today()
def Update():
    global t2 
    t1 = datetime.now()
    S = client.stock_quotes(symbols=list[0],  
             start=t2, end=t1).df

    d = deque()
    d.append(S)
    

    t2 = t1
    
    
Update()

In [ ]:
S_Quotes

                                         bid_price  bid_size bid_exchange  \
symbol timestamp
SYM    2026-02-10 00:08:31.539143+00:00      62.80     300.0            K
       2026-02-10 00:08:31.551128+00:00      62.80     300.0            K
       2026-02-10 00:47:51.877429+00:00      62.80     300.0            K
       2026-02-10 00:47:54.643956+00:00      62.80     300.0            K
       2026-02-10 00:47:54.644058+00:00      62.80     300.0            K
...                                            ...       ...          ...
       2026-02-18 17:01:14.035053+00:00      55.31     200.0            P
       2026-02-18 17:01:14.035097+00:00      55.31     200.0            P
       2026-02-18 17:01:14.041721+00:00      55.31     200.0            P
       2026-02-18 17:01:14.044376+00:00      55.31     100.0            P
       2026-02-18 17:01:17.150043+00:00      55.32     100.0            Q

                                         ask_price  ask_size ask_exchange  \
symbol timestamp
SYM    2026-02-10 00:08:31.539143+00:00      63.20     200.0            Q
       2026-02-10 00:08:31.551128+00:00      63.20     100.0            Q
       2026-02-10 00:47:51.877429+00:00      63.14     100.0            P
       2026-02-10 00:47:54.643956+00:00      63.13     100.0            P
       2026-02-10 00:47:54.644058+00:00      63.10     100.0            P
...                                            ...       ...          ...
       2026-02-18 17:01:14.035053+00:00      55.42     100.0            Q
       2026-02-18 17:01:14.035097+00:00      55.44     100.0            Q
       2026-02-18 17:01:14.041721+00:00      55.44     200.0            U
       2026-02-18 17:01:14.044376+00:00      55.44     200.0            U
       2026-02-18 17:01:17.150043+00:00      55.44     200.0            U

                                        conditions tape
symbol timestamp
SYM    2026-02-10 00:08:31.539143+00:00        [R]    C
       2026-02-10 00:08:31.551128+00:00        [R]    C
       2026-02-10 00:47:51.877429+00:00        [R]    C
       2026-02-10 00:47:54.643956+00:00        [R]    C
       2026-02-10 00:47:54.644058+00:00        [R]    C
...                                            ...  ...
       2026-02-18 17:01:14.035053+00:00        [R]    C
       2026-02-18 17:01:14.035097+00:00        [R]    C
       2026-02-18 17:01:14.041721+00:00        [R]    C
       2026-02-18 17:01:14.044376+00:00        [R]    C
       2026-02-18 17:01:17.150043+00:00        [R]    C

[93566 rows x 8 columns]

In [ ]:
#sum up all recurring size for a specific price: highlights where trades has occured more often 
from cudf import dtype

bid_x_size = pd.DataFrame(S_Quotes).reset_index().groupby('bid_price')['bid_size'].sum()
bid_x_size = bid_x_size.reset_index()

ask_x_size = (
    pd.DataFrame(S_Quotes)
      .reset_index()
      .groupby('ask_price')['ask_size']
      .sum()
      .reset_index()
)

In [ ]:
import pyqtgraph as pg 

offset = 0.5  # half a tick, adjust to your market

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)
p1 = win.addPlot(title = "bids")
p1.showGrid(x = True, y = True)
x1 = pg.BarGraphItem(x=bid_x_size.bid_price - offset, 
                     height=bid_x_size.bid_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(255,255,0))
p1.addItem(x1)

p1.setLabel('bottom', 'Price')
p1.setLabel('left', 'Bid Size')

win.nextRow()

p2 = win.addPlot(title = "asks")
p2.showGrid(x = True, y = True)

x2 = pg.BarGraphItem(x=ask_x_size.ask_price, 
                     height=ask_x_size.ask_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(0,255,255))




p2.addItem(x2)
app.exec()

Gtk-Message: 11:38:34.380: Failed to load module "appmenu-gtk-module"

0

In [ ]:
class Aggregations:
    def __init__(self, x: pd.DataFrame):
    
        pass 
    # Aggregations

In [ ]:
S_Bars['open'].diff()

symbol  timestamp
SYM     2026-01-26 09:00:00+00:00     NaN
        2026-01-26 09:01:00+00:00   -0.10
        2026-01-26 09:03:00+00:00    0.15
        2026-01-26 10:21:00+00:00   -0.79
        2026-01-26 12:05:00+00:00    0.41
                                     ...
        2026-02-06 11:01:00+00:00    0.01
        2026-02-06 11:02:00+00:00    0.27
        2026-02-06 11:07:00+00:00    0.79
        2026-02-06 11:25:00+00:00   -0.26
        2026-02-06 11:30:00+00:00    0.09
Name: open, Length: 4221, dtype: float64

In [ ]:
import numpy as np
from collections import deque
import pyqtgraph as pg
from PyQt6 import QtCore

app = pg.mkQApp("RT Scatter")

win = pg.GraphicsLayoutWidget(title="Real-time Scatter")
p = win.addPlot()
p.showGrid(x=True, y=True)

x = np.random.normal(1,3,100)
x2 = np.random.normal(1,3,100)
y = np.random.normal(1,3,100)


l = []
def update():

    print("hello")
  

timer = QtCore.QTimer()
timer.timeout.connect(Update)
timer.start(600)   # ~60 FPS

win.show()
pg.exec()

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

0

In [ ]:
print(type(z))

<class 'str'>