In [2]:
#from pydoc import cli

import numpy as np
#import incoming as inc
import matplotlib.pyplot as plt
import pandas as pd
from alpaca.data.historical import StockHistoricalDataClient, OptionHistoricalDataClient
from alpaca.data.requests import StockBarsRequest, StockQuotesRequest, OptionTradesRequest, OptionBarsRequest, OptionLatestQuoteRequest
OptionBarsRequest
from alpaca.data.enums import DataFeed
from alpaca.trading.enums import ContractType
from alpaca.trading.client import OptionContract, TradingClient, TradeAccount, GetOptionContractsRequest
from alpaca.data.timeframe import TimeFrame ; import cudf as cdf 
from datetime import datetime, timezone, date
import polars as pl
from alpaca.data.live import StockDataStream, OptionDataStream
from account import API_KEY , API_SECRET
from collections import  deque
import pyqtgraph as pg 

global  t2 

# alpaca_data_client.py

class AlpacaDataClient:
    def __init__(self, api_key: str, api_secret: str):
        self.stock_hist = StockHistoricalDataClient(api_key, api_secret)
        self.option_hist = OptionHistoricalDataClient(api_key, api_secret)

        
        self.stock_stream = StockDataStream(api_key, api_secret)
        self.option_stream = OptionDataStream(api_key, api_secret)

    # =========================
    # HISTORICAL — STOCKS
    # =========================
    def stock_bars(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = StockBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_bars(req)

    def stock_trades(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,

            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_trades(req)

    def stock_quotes(self, symbols, start=None, end=None
, limit=None, feed=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_quotes(req)

    # =========================
    # HISTORICAL — OPTIONS
    # =========================
    def option_bars(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = OptionBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit, 
            feed=feed
        )
        return self.option_hist.get_option_bars(req)

    def option_trades(self, symbols, start=None, end=None, limit=None, feed=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.option_hist.get_option_trades(req)

    def option_quotes(self, symbols, start=None, end=None, limit=None, feed=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed = feed
        )
        return self.option_hist.get_option_latest_quote(req)
    


    # =========================
    # STREAMING — STOCKS
    # =========================
    def stream_stock_bars(self, symbols, handler):
        self.stock_stream.subscribe_bars(handler, *symbols)

    def stream_stock_trades(self, symbols, handler):
        self.stock_stream.subscribe_trades(handler, *symbols)

    def stream_stock_quotes(self, symbols, handler):
        self.stock_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # STREAMING — OPTIONS
    # =========================
    def stream_option_trades(self, symbols, handler):
        self.option_stream.subscribe_trades(handler, *symbols)

    def stream_option_quotes(self, symbols, handler):
        self.option_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # RUN STREAMS
    # =========================
    async def run_stock_stream(self):
        await self.stock_stream.run()

    async def run_option_stream(self):
        await self.option_stream.run()

198000.51

TradingClient

In [3]:
class AlcapaTradingClient:
    def __init__(self, api_key: str, api_secret: str):
        self.contracts = TradingClient(
            api_key=api_key,
            secret_key=api_secret,
            paper=True
        )

    def contract(self, underlying_symbols, expiration_date,
                 strike_price_gte, strike_price_lte, type):

        req = GetOptionContractsRequest(
            underlying_symbols=underlying_symbols,  # FIXED
            expiration_date=expiration_date,
            strike_price_gte=strike_price_gte,
            strike_price_lte=strike_price_lte,
            type=type
        )

        return self.contracts.get_option_contracts(req)


tradeClient = AlcapaTradingClient(API_KEY, API_SECRET)

all_contracts = tradeClient.contract(
    underlying_symbols=["AAPL"],
    expiration_date="2026-01-21",
    strike_price_gte="150",
    strike_price_lte="200",
    type=ContractType.CALL
)

In [4]:
all_contracts

{'next_page_token': None, 'option_contracts': []}

ReQuests

In [5]:


list = ["SYM", "INTC", "NVDA", "ARM", "AMD"]
start_date = datetime(2026,2, 25).date()
end_date = datetime.now()
x = list[0]

def MakeOptionsym(sym:str, type: str, date : datetime, strike):
    date =  date.strftime("%y%m%d")
    strike = int(round(strike * 1000))
    pad = 8 - len(str(strike))
    pad = str(0).zfill(pad)
    lowStrike = 100
    highStrik = 300
    i = sym+str(date)+type+str(pad)+str(strike)
    return i

z = MakeOptionsym(list[1],"C",datetime(2026,1,30), 75)
print(z)
l = "INTC260130C00060000"
start_date

INTC260130C00075000

datetime.date(2026, 2, 25)

In [6]:
client  = AlpacaDataClient(API_KEY, API_SECRET) 
S_Quotes = client.stock_quotes(symbols=x,  start=start_date, end=end_date, feed=DataFeed.SIP).df
S_Bars = client.stock_bars(symbols=x,timeframe=TimeFrame.Minute, start=start_date, end=end_date, feed=DataFeed.SIP).df
S_Trades = client.stock_trades(symbols=x,timeframe=TimeFrame.Minute,start=start_date, end=end_date,feed=DataFeed.SIP).df

In [7]:
S_Bars = S_Bars.reset_index()
S_Bars['timestamp'] = S_Bars['timestamp'].view('int64') // 10**6
S_Bars

/tmp/ipykernel_16589/2846544688.py:2: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  S_Bars['timestamp'] = S_Bars['timestamp'].view('int64') // 10**6

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,SYM,1771980180000,56.530,56.530,56.530,56.530,127.0,2.0,56.530
1,SYM,1771980660000,56.490,56.490,56.490,56.490,100.0,1.0,56.490
2,SYM,1771980720000,56.560,56.560,56.560,56.560,150.0,5.0,56.560
3,SYM,1771981080000,56.560,56.560,56.560,56.560,120.0,4.0,56.560
4,SYM,1772017020000,56.750,56.750,56.750,56.750,474.0,3.0,56.750
...,...,...,...,...,...,...,...,...,...
3136,SYM,1772841780000,49.090,49.090,49.090,49.090,200.0,2.0,49.090
3137,SYM,1772842560000,49.045,49.045,49.045,49.045,277.0,4.0,49.045
3138,SYM,1772843100000,48.940,48.940,48.940,48.940,118.0,4.0,48.940
3139,SYM,1772844300000,48.820,48.820,48.820,48.820,120.0,2.0,48.820
3140,SYM,1772845140000,48.740,48.740,48.740,48.740,1502.0,5.0,48.740

In [8]:


#O_Quotes = client.option_quotes(z, start=start_date, end=datetime.today())
O_Bars = client.option_bars([z,l],timeframe=TimeFrame.Hour,start= start_date, end=datetime.today())
O_Trades = client.option_trades(z, start=start_date, end=datetime.today())

In [12]:
X_bars = S_Bars[['volume', 'timestamp', 'vwap']]
S_Trades

                                        exchange    price    size     id  \
symbol timestamp
SYM    2026-02-25 00:00:02.461174+00:00        D  56.3100     4.0  10360
       2026-02-25 00:03:45.019717+00:00        Y  56.3700     1.0     88
       2026-02-25 00:03:45.021073+00:00        D  56.3900     1.0  10361
       2026-02-25 00:06:22.022175+00:00        D  56.5146     7.0  10362
       2026-02-25 00:06:53.081605+00:00        D  56.5500     1.0  10363
...                                          ...      ...     ...    ...
       2026-03-07 00:59:17.904817+00:00        P  48.7500    35.0   2928
       2026-03-07 00:59:17.904818+00:00        P  48.7500    59.0   2929
       2026-03-07 00:59:17.905617+00:00        D  48.7400  1200.0  16915
       2026-03-07 00:59:17.906294+00:00        P  48.7400   198.0   2930
       2026-03-07 00:59:39.943771+00:00        D  48.6900    10.0  16916

                                        conditions tape
symbol timestamp
SYM    2026-02-25 00:00:02.461174+00:00  [@, T, I]    C
       2026-02-25 00:03:45.019717+00:00  [@, T, I]    C
       2026-02-25 00:03:45.021073+00:00  [@, T, I]    C
       2026-02-25 00:06:22.022175+00:00  [@, T, I]    C
       2026-02-25 00:06:53.081605+00:00  [@, T, I]    C
...                                            ...  ...
       2026-03-07 00:59:17.904817+00:00  [@, T, I]    C
       2026-03-07 00:59:17.904818+00:00  [@, T, I]    C
       2026-03-07 00:59:17.905617+00:00     [@, T]    C
       2026-03-07 00:59:17.906294+00:00     [@, T]    C
       2026-03-07 00:59:39.943771+00:00  [@, T, I]    C

[187812 rows x 6 columns]

In [ ]:
from cudf import dtype
import cupy as cp
from cuml.cluster import HDBSCAN
#from sklearn.cluster import HDBSCAN
import numpy as np




# GPU array
X = np.asarray(X, dtype='float32').reshape(-1,1)

clusterer = HDBSCAN(
    min_cluster_size=2,
    min_samples=2,
    metric="euclidean",
    prediction_data=True
)

clusterer.fit_predict(X)

lables = clusterer.n_clusters_

prob = clusterer.labels_.tolist()


print(prob)

NameError: name 't' is not defined

In [ ]:
import time
from datetime import datetime
from numpy import size
import pyqtgraph as pg
from PyQt6 import QtCore

y = S_Bars['trade_count']
t = S_Bars['timestamp'].to_numpy().astype("datetime64[ns]").view("int64") / 1e9
v = S_Bars['volume']
dV = np.gradient(v) 

v = np.array(v)


app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show= True, title="Graph")
p1 = win.addPlot()
p1.showGrid(x=True, y=True)
sc = pg.PlotCurveItem()
p1.addItem(sc)
n = 0


def update():
    global n
    print("hello")
    sc.setData(v[:n+1])
    n = (n +1)

  
            
timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(6)   # ~60 FPS

win.show()
app.exec()

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

0

In [ ]:

S_Quotes

                                         bid_price  bid_size bid_exchange  \
symbol timestamp
SYM    2026-02-25 00:32:57.586174+00:00      56.25     200.0            Q
       2026-02-25 00:40:49.101994+00:00      56.25     200.0            Q
       2026-02-25 00:40:57.667343+00:00      56.25     200.0            Q
       2026-02-25 00:41:44.269406+00:00      56.25     200.0            Q
       2026-02-25 00:50:02.280031+00:00      56.23     200.0            P
...                                            ...       ...          ...
       2026-03-07 00:59:17.906299+00:00      48.50     300.0            P
       2026-03-07 00:59:17.906350+00:00      48.50     300.0            P
       2026-03-07 00:59:17.908309+00:00      48.50     300.0            P
       2026-03-07 00:59:17.908352+00:00      48.50     300.0            P
       2026-03-07 00:59:50.521606+00:00      48.50     300.0            P

                                         ask_price  ask_size ask_exchange  \
symbol timestamp
SYM    2026-02-25 00:32:57.586174+00:00      56.55     100.0            P
       2026-02-25 00:40:49.101994+00:00      56.55     200.0            P
       2026-02-25 00:40:57.667343+00:00      56.55     100.0            P
       2026-02-25 00:41:44.269406+00:00      56.55     200.0            P
       2026-02-25 00:50:02.280031+00:00      56.55     200.0            P
...                                            ...       ...          ...
       2026-03-07 00:59:17.906299+00:00      49.10     200.0            P
       2026-03-07 00:59:17.906350+00:00      48.81     100.0            P
       2026-03-07 00:59:17.908309+00:00      48.69     300.0            P
       2026-03-07 00:59:17.908352+00:00      48.69     400.0            P
       2026-03-07 00:59:50.521606+00:00      48.69     500.0            P

                                        conditions tape
symbol timestamp
SYM    2026-02-25 00:32:57.586174+00:00        [R]    C
       2026-02-25 00:40:49.101994+00:00        [R]    C
       2026-02-25 00:40:57.667343+00:00        [R]    C
       2026-02-25 00:41:44.269406+00:00        [R]    C
       2026-02-25 00:50:02.280031+00:00        [R]    C
...                                            ...  ...
       2026-03-07 00:59:17.906299+00:00        [R]    C
       2026-03-07 00:59:17.906350+00:00        [R]    C
       2026-03-07 00:59:17.908309+00:00        [R]    C
       2026-03-07 00:59:17.908352+00:00        [R]    C
       2026-03-07 00:59:50.521606+00:00        [R]    C

[119813 rows x 8 columns]

In [ ]:
#sum up all recurring size for a specific price: highlights where trades has occured more often 
from cudf import dtype

bid_x_size = pd.DataFrame(S_Quotes).reset_index().groupby('bid_price')['bid_size'].sum().reset_index()


filtered = pd.DataFrame(S_Quotes[S_Quotes['bid_size']> 10])

ask_x_size = (
    pd.DataFrame(S_Quotes)
      .reset_index()
      .groupby('ask_price')['ask_size']
      .sum()
      .reset_index()
)

bid_x_size

     bid_price  bid_size
0        25.50     500.0
1        26.50     500.0
2        26.75     500.0
3        30.00     300.0
4        33.40     100.0
..         ...       ...
935      57.77     300.0
936      57.78    1200.0
937      57.79     100.0
938      57.80     500.0
939      57.81     900.0

[940 rows x 2 columns]

In [ ]:
import pyqtgraph as pg 

offset = 0.5  # half a tick, adjust to your market

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)
p1 = win.addPlot(title = "bids")
p1.showGrid(x = True, y = True)
x1 = pg.BarGraphItem(x=bid_x_size.bid_price - offset, 
                     height=bid_x_size.bid_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(255,255,0))
p1.addItem(x1)

p1.setLabel('bottom', 'Price')
p1.setLabel('left', 'Bid Size')

win.nextRow()

p2 = win.addPlot(title = "asks")
p2.showGrid(x = True, y = True)

x2 = pg.BarGraphItem(x=ask_x_size.ask_price - offset, 
                     height=ask_x_size.ask_size , width = 0.09, 
                     size=0.3, brush = pg.mkBrush(0,255,255))


p2.addItem(x2)
app.exec()

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

hello

RuntimeError: wrapped C/C++ object of type PlotCurveItem has been deleted

0

In [ ]:
class Aggregations:
    def __init__(self, x: pd.DataFrame):
    
        pass 
    # Aggregations

In [ ]:
S_Bars['open'].diff()

0         NaN
1      -0.040
2       0.070
3       0.000
4       0.190
        ...
3136    0.240
3137   -0.045
3138   -0.105
3139   -0.120
3140   -0.080
Name: open, Length: 3141, dtype: float64

In [ ]:
import numpy as np
from collections import deque
import pyqtgraph as pg
from PyQt6 import QtCore
from realtime import stock_quotes

app = pg.mkQApp("RT Scatter")

win = pg.GraphicsLayoutWidget(title="Real-time Scatter")
p = win.addPlot()
p.showGrid(x=True, y=True)

x = np.random.normal(1,3,100)
x2 = np.random.normal(1,3,100)
y = np.random.normal(1,3,100)


l = []
def update():
    print(len(stock_quotes))

timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(600)   # ~60 FPS

win.show()
pg.exec()

ImportError: cannot import name 'stock_quotes' from 'realtime' (/home/nvitop/Shared/Investing/realtime.py)

In [ ]:
print(type(z))

<class 'str'>

In [ ]:
symbols = ["SYM", "INTC", "NVDA", "ARM", "AMD"]
start_date = datetime(2026,2, 25).date()
end_date = datetime.now()
x = symbols[0]



def MakeOptionsym(sym: list, type: str, date: datetime, strike: list):
    symbols = []
    date = date.strftime("%y%m%d")

    for s in sym:
        for i in strike:
            strike_val = int(round(i * 1000))
            pad = 8 - len(str(strike_val))
            pad = "0" * pad

            symbols.append(s + str(date) + type + pad + str(strike_val))
    return symbols

syms = ["INTC", "NVDA"]
strikes = [10, 30, 50]
z = MakeOptionsym(syms, "C", datetime(2026,4,24), strikes)
print(z)