In [ ]:
#from pydoc import cli

import numpy as np
#import incoming as inc
import matplotlib.pyplot as plt
import pandas as pd
from alpaca.data.historical import StockHistoricalDataClient, OptionHistoricalDataClient
from alpaca.data.requests import StockBarsRequest, StockQuotesRequest, OptionTradesRequest, OptionBarsRequest, OptionLatestQuoteRequest
OptionBarsRequest

from alpaca.trading.client import OptionContract, TradingClient, TradeAccount, GetOptionContractsRequest
from alpaca.data.timeframe import TimeFrame ; import cudf as cdf 
from datetime import datetime, timezone, date
import polars as pl
from alpaca.data.live import StockDataStream, OptionDataStream
from account import API_KEY , API_SECRET
from collections import  deque
import pyqtgraph as pg 

global  t2 

# alpaca_data_client.py

class AlpacaDataClient:
    def __init__(self, api_key: str, api_secret: str):
        self.stock_hist = StockHistoricalDataClient(api_key, api_secret)
        self.option_hist = OptionHistoricalDataClient(api_key, api_secret)

        
        self.stock_stream = StockDataStream(api_key, api_secret)
        self.option_stream = OptionDataStream(api_key, api_secret)

    # =========================
    # HISTORICAL — STOCKS
    # =========================
    def stock_bars(self, symbols, timeframe, start=None, end=None, limit=None):
        req = StockBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_bars(req)

    def stock_trades(self, symbols, timeframe, start=None, end=None, limit=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,

            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_trades(req)

    def stock_quotes(self, symbols, start=None, end=None
, limit=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.stock_hist.get_stock_quotes(req)

    # =========================
    # HISTORICAL — OPTIONS
    # =========================
    def option_bars(self, symbols, timeframe, start=None, end=None, limit=None):
        req = OptionBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_bars(req)

    def option_trades(self, symbols, start=None, end=None, limit=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_trades(req)

    def option_quotes(self, symbols, start=None, end=None, limit=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit
        )
        return self.option_hist.get_option_latest_quote(req)
    


    # =========================
    # STREAMING — STOCKS
    # =========================
    def stream_stock_bars(self, symbols, handler):
        self.stock_stream.subscribe_bars(handler, *symbols)

    def stream_stock_trades(self, symbols, handler):
        self.stock_stream.subscribe_trades(handler, *symbols)

    def stream_stock_quotes(self, symbols, handler):
        self.stock_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # STREAMING — OPTIONS
    # =========================
    def stream_option_trades(self, symbols, handler):
        self.option_stream.subscribe_trades(handler, *symbols)

    def stream_option_quotes(self, symbols, handler):
        self.option_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # RUN STREAMS
    # =========================
    async def run_stock_stream(self):
        await self.stock_stream.run()

    async def run_option_stream(self):
        await self.option_stream.run()

199642.6

In [ ]:
class AlcapaTradingClient:
    def __init__(self, api_key: str, api_secret: str):
        self.contracts = TradingClient(api_key=api_key, secret_key=api_secret, paper=True)


    def contract(self, underlying_symbol,expiration_date, strike_price_gte, strike_price_lte, type):
        req = GetOptionContractsRequest(
               underlying_symbol=underlying_symbol,
                expiration_date=expiration_date,
                strike_price_gte=strike_price_gte,
                strike_price_lte=strike_price_lte,
                type=type
                                )
        return self.contracts.get_option_contracts(req)

        
p = AlcapaTradingClient(API_KEY, API_SECRET)
p.contracts()

ReQuests

In [ ]:
list = ["SYM", "INTC", "NVDA", "ARM", "AMD"]
start_date = datetime(2026,2, 19)
end_date = datetime.now()
x = list[1]



def MakeOptionsym(sym:str, type: str, date : datetime, strike):
    date =  date.strftime("%y%m%d")
    strike = int(round(strike * 1000))
    pad = 8 - len(str(strike))
    pad = str(0).zfill(pad)
    i = sym+str(date)+type+str(pad)+str(strike)
    return i

z = MakeOptionsym(list[1],"C",datetime(2026,1,30), 75)
print(z)

INTC260130C00075000

In [21]:
client  = AlpacaDataClient(API_KEY, API_SECRET) 
S_Quotes = client.stock_quotes(symbols=x,   start=start_date, end=datetime.now()).df
S_Bars = client.stock_bars(symbols=x,timeframe=TimeFrame.Minute, start=start_date, end=datetime.today()).df
S_Trades = client.stock_trades(symbols=x,timeframe=TimeFrame.Minute,start=start_date, end=datetime.today()).df
# remeber old time and call
#  and new time and add the data frame btw those times

In [22]:
S_Bars = S_Bars.reset_index()
S_Bars

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,INTC,2026-02-19 00:01:00+00:00,45.4500,45.4500,45.4200,45.4200,3384.0,21.0,45.446137
1,INTC,2026-02-19 00:02:00+00:00,45.4300,45.4300,45.4300,45.4300,237.0,6.0,45.430000
2,INTC,2026-02-19 00:03:00+00:00,45.4300,45.4300,45.4300,45.4300,833.0,26.0,45.430000
3,INTC,2026-02-19 00:04:00+00:00,45.4200,45.4200,45.4200,45.4200,553.0,5.0,45.420000
4,INTC,2026-02-19 00:05:00+00:00,45.4201,45.4201,45.4201,45.4201,177.0,6.0,45.420100
...,...,...,...,...,...,...,...,...,...
1634,INTC,2026-02-21 00:55:00+00:00,44.0018,44.0100,44.0018,44.0100,2157.0,11.0,44.006470
1635,INTC,2026-02-21 00:56:00+00:00,44.0000,44.0100,44.0000,44.0100,1597.0,11.0,44.008553
1636,INTC,2026-02-21 00:57:00+00:00,44.0100,44.0100,44.0000,44.0000,1178.0,15.0,44.006733
1637,INTC,2026-02-21 00:58:00+00:00,44.0098,44.0100,44.0000,44.0083,14506.0,33.0,44.005546
1638,INTC,2026-02-21 00:59:00+00:00,44.0000,44.0100,44.0000,44.0100,11095.0,36.0,44.005906

In [6]:

#Options 
#O_Quotes = client.option_quotes(z, start=start_date, end=datetime.today())
O_Bars = client.option_bars(z,timeframe=TimeFrame.Hour,start= start_date, end=datetime.today())
O_Trades = client.option_trades(z, start=start_date, end=datetime.today())

In [17]:
y = S_Bars['trade_count']
t = S_Bars['timestamp'].to_numpy().astype("datetime64[ns]").view("int64") / 1e9 / 60
v = S_Bars['volume']
f = np.gradient(v, t)
f

import numpy as np
import pandas as pd
import pyqtgraph as pg

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)


cumV = np.cumsum(v)                  # integral (total volume so far)
rate = np.gradient(cumV, t)          # volume-per-second (should be >= 0 mostly)

p1 = win.addPlot(title="Cumulative Volume (Integral)")
p1.showGrid(x=True, y=True)
p1.plot(t, cumV, pen=pg.mkPen('y', width=2))
win.nextRow()

p2 = win.addPlot(title="Rate of Cumulative Volume (dCumV/dt)")
p2.showGrid(x=True, y=True)
p2.plot(t, rate, pen=pg.mkPen('c', width=2))

app.exec()

/tmp/ipykernel_29016/1830208075.py:2: UserWarning: no explicit representation of timezones available for np.datetime64
  t = S_Bars['timestamp'].to_numpy().astype("datetime64[ns]").view("int64") / 1e9 / 60

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

0

In [8]:
rate

array([6.57500000e+01, 9.53750000e+01, 1.24002688e+02, 9.32418596e+01,
       7.97698563e+01, 4.53823529e+01, 9.90529412e+02, 7.50333333e+02,
       1.45215539e+02, 6.36109840e+01, 5.87500000e+01, 2.35375000e+01,
       1.69355377e+01, 4.57360360e+02, 4.04237500e+02, 6.82717105e+01,
       2.44766942e+01, 3.65209150e+02, 3.35150000e+03, 5.46800000e+03,
       2.40650000e+03, 3.50000000e+02, 3.43000000e+02, 1.75500000e+02,
       1.60857143e+02, 8.50000000e+01, 1.14666667e+02, 1.21875000e+02,
       1.15111111e+02, 2.45766667e+02, 1.08216667e+03, 1.36553333e+03,
       9.43333333e+01, 2.31000000e+02, 3.13476190e+02, 6.45686275e+01,
       9.92692308e+01, 1.19000000e+02, 1.83125000e+02, 1.53447552e+02,
       2.29601399e+02, 5.94333333e+02, 1.80358333e+03, 3.09370000e+04,
       3.23530000e+04, 7.82600000e+03, 6.42750000e+03, 6.19950000e+03,
       9.22700000e+03, 6.33600000e+03, 5.06800000e+03, 4.08100000e+03,
       5.04000000e+03, 5.91850000e+03, 3.95150000e+03, 5.32450000e+03,
       4.58000000e+03, 2.39350000e+03, 5.39750000e+03, 7.46550000e+03,
       4.25100000e+03, 1.93900000e+03, 4.76300000e+03, 6.08700000e+03,
       5.93800000e+03, 8.42850000e+03, 7.10450000e+03, 3.88900000e+03,
       7.64350000e+03, 9.11700000e+03, 5.37500000e+03, 5.43400000e+03,
       3.65500000e+03, 1.66000000e+03, 1.77150000e+03, 8.08000000e+02,
       4.43700000e+03, 7.79700000e+03, 4.40850000e+03, 3.21400000e+03,
       2.96400000e+03, 2.70150000e+03, 2.71950000e+03, 1.41400000e+03,
       1.63650000e+03, 4.17350000e+03, 3.62900000e+03, 1.76550000e+03,
       2.38900000e+03, 1.59700000e+03, 2.97800000e+03, 3.58400000e+03,
       2.17150000e+03, 1.26050000e+03, 2.83800000e+03, 3.26833333e+03,
       4.79766667e+03, 3.95750000e+03, 2.50150000e+03, 2.44400000e+03,
       6.06500000e+02, 1.55900000e+03, 1.82000000e+03, 2.49600000e+03,
       4.81450000e+03, 3.63750000e+03, 1.69650000e+03, 1.62850000e+03,
       2.19650000e+03, 2.70000000e+03, 1.69450000e+03, 1.02450000e+03,
       1.01250000e+03, 1.18850000e+03, 1.47100000e+03, 1.81250000e+03,
       3.48450000e+03, 3.27900000e+03, 2.54900000e+03, 2.27050000e+03,
       1.03550000e+03, 1.32050000e+03, 1.66600000e+03, 1.20216667e+03,
       3.71883333e+03, 3.78700000e+03, 1.65100000e+03, 2.85550000e+03,
       4.50700000e+03, 4.70800000e+03, 3.79150000e+03, 2.08800000e+03,
       9.19000000e+02, 1.02350000e+03, 2.42650000e+03, 3.89750000e+03,
       3.77150000e+03, 2.39450000e+03, 1.48750000e+03, 9.31500000e+02,
       1.25750000e+03, 2.07650000e+03, 2.60650000e+03, 1.58950000e+03,
       1.10850000e+03, 1.07950000e+03, 2.10150000e+03, 2.82150000e+03,
       1.50350000e+03, 1.85950000e+03, 2.99250000e+03, 5.69200000e+03,
       4.54150000e+03, 7.18500000e+02, 1.36100000e+03, 3.09450000e+03,
       3.04500000e+03, 1.69150000e+03, 1.75100000e+03, 2.00150000e+03,
       1.04500000e+03, 7.47000000e+02, 9.13500000e+02, 5.08500000e+02,
       3.88500000e+02, 1.80200000e+03, 2.13650000e+03, 1.05300000e+03,
       7.27500000e+02, 4.43500000e+02, 4.78600000e+03, 5.33250000e+03,
       1.62800000e+03, 1.32216667e+03, 5.43150000e+03, 4.25250000e+03,
       9.37000000e+02, 1.35250000e+03, 8.59500000e+02, 7.04500000e+02,
       2.69950000e+03, 2.49300000e+03, 4.15500000e+02, 1.08200000e+03,
       1.27650000e+03, 6.70000000e+02, 1.36200000e+03, 1.61750000e+03,
       2.52250000e+03, 2.01800000e+03, 2.70500000e+02, 1.03950000e+03,
       1.87100000e+03, 1.40650000e+03, 8.64000000e+02, 6.77500000e+02,
       4.92950000e+03, 6.63450000e+03, 2.67216667e+03, 3.21000000e+02,
       2.29916667e+03, 2.09250000e+03, 1.19400000e+03, 1.60950000e+03,
       1.32533333e+03, 1.09333333e+03, 2.05800000e+03, 1.75700000e+03,
       7.13500000e+02, 6.52500000e+02, 7.24500000e+02, 1.02900000e+03,
       2.56550000e+03, 2.47250000e+03, 2.12650000e+03, 1.80950000e+03,
       7.06500000e+02, 1.39150000e+03, 2.79900000e+03, 2.35300000e+03,
       7.31000000e+02, 5.64000000e+02, 1.04100000e+03, 1.11650000e+03,
       1.68050000e+03, 2.33050000e+03, 1.49800000e+03, 5.52000000e+02,
       4.56000000e+02, 1.17100000e+03, 1.75450000e+03, 2.26250000e+03,
       2.02350000e+03, 9.72000000e+02, 4.20000000e+02, 1.68900000e+03,
       1.73100000e+03, 5.16500000e+02, 1.17000000e+03, 1.81000000e+03,
       1.67350000e+03, 1.36350000e+03, 1.61200000e+03, 1.69935000e+03,
       6.68150000e+02, 8.97333333e+02, 1.08675000e+03, 2.96650000e+03,
       2.91750000e+03, 2.50600000e+03, 2.74700000e+03, 2.65900000e+03,
       1.62450000e+03, 1.76400000e+03, 1.80200000e+03, 8.03500000e+02,
       1.88900000e+03, 1.66450000e+03, 1.07700000e+03, 1.00208333e+03,
       1.29158333e+03, 1.02600000e+03, 3.65000000e+02, 5.74500000e+02,
       5.94000000e+02, 8.99500000e+02, 1.21266667e+03, 7.06500000e+02,
       4.59500000e+02, 9.50666667e+02, 1.71850000e+03, 1.72600000e+03,
       1.03475000e+03, 9.69285714e+01, 4.32700000e+02, 9.72000000e+02,
       4.72200000e+03, 5.31100000e+03, 4.43200000e+03, 3.53900000e+03,
       8.16000000e+02, 9.14500000e+02, 1.69750000e+03, 1.66416667e+03,
       4.14166667e+02, 3.80000000e+02, 7.52500000e+02, 4.26850000e+03,
       4.03200000e+03, 6.08000000e+02, 2.26350000e+03, 2.83933333e+03,
       4.64666667e+02, 5.35833333e+02, 1.84983333e+03, 1.94550000e+03,
       8.68000000e+02, 7.87000000e+02, 1.47700000e+03, 5.38550000e+03,
       4.70300000e+03, 1.58850000e+03, 1.70400000e+03, 1.44700000e+03,
       1.78650000e+03, 2.94550000e+03, 3.18616667e+03, 5.28166667e+02,
       1.86350000e+03, 2.77900000e+03, 1.44450000e+03, 3.30000000e+02,
       7.43500000e+02, 7.80500000e+02, 9.63000000e+02, 1.21700000e+03,
       7.69000000e+02, 1.10490000e+04, 1.20120000e+04, 3.31350000e+03,
       2.16650000e+03, 1.20400000e+03, 7.75850000e+03, 7.97500000e+03,
       1.48900000e+03, 3.90000000e+02, 4.97500000e+02, 1.49750000e+03,
       1.66650000e+03, 3.40400000e+03, 4.33750000e+03, 1.98300000e+03,
       4.94800000e+03, 5.15900000e+03, 5.83050000e+03, 6.78950000e+03,
       1.94450000e+03, 5.67000000e+02, 2.60600000e+03, 2.78000000e+03,
       4.94100000e+03, 6.01016667e+03, 3.61816667e+03, 4.51800000e+03,
       4.07850000e+03, 1.02836667e+04, 7.81900000e+03, 3.30000000e+03,
       5.53850000e+03, 4.05000000e+03, 1.95650000e+03, 2.48250000e+03,
       1.92350000e+03, 3.00700000e+03, 3.70800000e+03, 2.97150000e+03,
       5.10450000e+03, 4.28250000e+03, 3.48500000e+03, 3.29700000e+03,
       1.38600000e+03, 4.63500000e+03, 5.00600000e+03, 6.31700000e+03,
       8.85600000e+03, 4.45850000e+03, 9.54500000e+02, 1.45550000e+03,
       1.58050000e+03, 2.47916667e+03, 3.36233333e+03, 3.25633333e+03,
       3.14200000e+03, 8.38400000e+03, 7.22250000e+03, 9.71500000e+02,
       3.21050000e+03, 5.20900000e+03, 4.13200000e+03, 1.89400000e+03,
       1.93450000e+03, 3.75000000e+03, 5.78150000e+03, 5.38050000e+03,
       3.54150000e+03, 3.42650000e+03, 2.20230000e+04, 2.10725000e+04,
       1.81000000e+03, 4.94750000e+03, 5.64250000e+03, 4.12000000e+03,
       3.57050000e+03, 4.55350000e+03, 8.88950000e+03, 1.05125000e+04,
       1.05095000e+04, 1.03920000e+04, 1.11025000e+04, 1.05195000e+04,
       9.51400000e+03, 1.44150000e+04, 2.88145000e+04, 5.10285000e+04,
       4.17128333e+04, 8.90833333e+01, 1.28333333e+01, 1.09678266e+01,
       2.90906018e+00, 4.09953637e+00, 4.48075752e+00, 3.49063355e+00,
       1.01890410e+01, 9.74964912e+00, 9.90978417e+00, 1.94833333e+02,
       2.17250000e+02, 1.89253030e+03, 1.85527083e+03, 9.00570175e+01,
       8.56984848e+01, 5.34098485e+02, 8.44000000e+02, 9.72232143e+02,
       2.87107143e+02, 2.71950000e+02, 2.18250000e+02, 2.46385714e+02,
       7.10285714e+01, 2.89333333e+02, 3.82371429e+02, 1.42238095e+02,
       1.30823810e+02, 3.58699634e+01, 2.14869394e+03, 2.21680000e+03,
       3.55050000e+03, 3.25450000e+03, 2.25500000e+03, 7.15000000e+03,
       6.66800000e+03, 5.12550000e+03, 4.70500000e+03, 4.55550000e+03,
       6.54400000e+03, 7.04250000e+03, 6.31400000e+03, 3.62700000e+03,
       8.96950000e+03, 1.07465000e+04, 1.04805000e+04, 9.19900000e+03,
       3.69150000e+03, 2.22350000e+03, 5.17850000e+03, 8.83550000e+03,
       3.95775000e+04, 4.45410000e+04, 1.43425000e+04, 6.93300000e+03,
       4.77100000e+03, 4.90500000e+03, 1.53825000e+04, 1.78050000e+04,
       6.66400000e+03, 1.84625000e+04, 2.20955000e+04, 1.13720000e+04,
       7.07650000e+03, 2.98650000e+03, 3.87500000e+03, 4.26400000e+03,
       3.11700000e+03, 2.59350000e+03, 2.84900000e+03, 5.85900000e+03,
       1.02255000e+04, 6.86050000e+03, 1.98200000e+03, 3.55800000e+03,
       5.24500000e+03, 5.19000000e+03, 2.97300000e+03, 2.02900000e+03,
       4.73200000e+03, 5.47850000e+03, 2.97800000e+03, 1.80350000e+03,
       2.36300000e+03, 2.85650000e+03, 3.05600000e+03, 2.38500000e+03,
       2.19350000e+03, 2.87700000e+03, 2.53100000e+03, 2.82700000e+03,
       2.88750000e+03, 1.79050000e+03, 1.20400000e+03, 1.71350000e+03,
       5.45450000e+03, 4.42000000e+03, 7.22000000e+02, 1.97100000e+03,
       3.86300000e+03, 3.28200000e+03, 1.38950000e+03, 1.66800000e+03,
       3.52100000e+03, 2.60750000e+03, 1.35850000e+03, 3.29900000e+03,
       3.74250000e+03, 3.84050000e+03, 4.65500000e+03, 2.97350000e+03,
       1.36850000e+03, 1.25250000e+03, 2.24850000e+03, 3.30800000e+03,
       2.21450000e+03, 1.13450000e+03, 1.55550000e+03, 2.19600000e+03,
       3.38900000e+03, 2.78050000e+03, 2.33200000e+03, 1.71350000e+03,
       1.34150000e+03, 1.76300000e+03, 1.36350000e+03, 9.65000000e+02,
       5.09500000e+02, 1.99300000e+03, 2.17700000e+03, 2.73100000e+03,
       3.98050000e+03, 2.52450000e+03, 3.60550000e+03, 4.04350000e+03,
       3.18250000e+03, 2.67500000e+03, 1.79750000e+03, 5.98750000e+03,
       6.64100000e+03, 4.13850000e+03, 3.81750000e+03, 1.74350000e+03,
       1.86700000e+03, 3.96100000e+03, 6.07600000e+03, 5.30800000e+03,
       2.53200000e+03, 1.41300000e+03, 1.10150000e+03, 2.44000000e+03,
       4.26650000e+03, 3.31350000e+03, 1.81350000e+03, 2.08050000e+03,
       1.66100000e+03, 1.57750000e+03, 2.76800000e+03, 5.95700000e+03,
       7.07400000e+03, 3.74500000e+03, 2.58650000e+03, 6.10400000e+03,
       5.49700000e+03, 2.01100000e+03, 1.91050000e+03, 1.87200000e+03,
       2.64600000e+03, 6.32900000e+03, 5.77850000e+03, 2.09750000e+03,
       2.15200000e+03, 1.46700000e+03, 7.78500000e+02, 1.33050000e+03,
       1.37050000e+03, 3.22700000e+03, 5.50050000e+03, 3.47250000e+03,
       1.40850000e+03, 1.59650000e+03, 2.45500000e+03, 1.94850000e+03,
       9.06500000e+02, 1.05200000e+03, 1.17650000e+03, 1.55900000e+03,
       4.57500000e+03, 5.55050000e+03, 4.20250000e+03, 3.44550000e+03,
       1.59800000e+03, 3.31650000e+03, 1.00985000e+04, 1.09100000e+04,
       4.37650000e+03, 2.16350000e+03, 1.87050000e+03, 3.57300000e+03,
       4.06950000e+03, 2.55200000e+03, 5.64500000e+03, 6.95550000e+03,
       3.54750000e+03, 1.35650000e+03, 1.86650000e+03, 3.64350000e+03,
       3.52500000e+03, 4.44200000e+03, 3.92400000e+03, 1.11300000e+03,
       2.37400000e+03, 2.10450000e+03, 1.30200000e+03, 2.00950000e+03,
       1.74150000e+03, 1.46100000e+03, 1.70750000e+03, 1.37750000e+03,
       7.73000000e+02, 4.97500000e+02, 3.25600000e+03, 4.28450000e+03,
       2.85700000e+03, 2.85850000e+03, 1.77900000e+03, 1.86250000e+03,
       3.49300000e+03, 2.93700000e+03, 1.83250000e+03, 1.52100000e+03,
       1.92500000e+03, 2.83150000e+03, 2.90750000e+03, 2.58750000e+03,
       1.56800000e+03, 1.08850000e+03, 1.64750000e+03, 1.99900000e+03,
       2.51100000e+03, 3.22950000e+03, 1.90200000e+03, 6.70000000e+02,
       5.40500000e+02, 4.60000000e+02, 6.12000000e+02, 8.30000000e+02,
       7.45500000e+02, 1.16950000e+03, 1.06850000e+03, 2.01750000e+03,
       2.28000000e+03, 2.20450000e+03, 2.31350000e+03, 1.03100000e+03,
       9.31000000e+02, 3.60650000e+03, 4.43300000e+03, 2.64100000e+03,
       3.02200000e+03, 4.52400000e+03, 3.91100000e+03, 2.27250000e+03,
       2.61950000e+03, 2.35550000e+03, 1.73300000e+03, 1.90350000e+03,
       7.46050000e+03, 7.39350000e+03, 4.06250000e+03, 4.27350000e+03,
       1.85450000e+03, 2.40500000e+03, 3.08800000e+03, 3.22600000e+03,
       2.52400000e+03, 1.83350000e+03, 2.65850000e+03, 2.03150000e+03,
       9.06500000e+02, 1.83950000e+03, 2.34150000e+03, 1.67700000e+03,
       4.44700000e+03, 3.95900000e+03, 1.19200000e+03, 1.69700000e+03,
       1.71000000e+03, 1.53700000e+03, 1.85800000e+03, 1.67650000e+03,
       1.25400000e+03, 1.04000000e+03, 2.67900000e+03, 4.02850000e+03,
       2.08300000e+03, 6.95000000e+02, 9.44000000e+02, 2.18950000e+03,
       2.35100000e+03, 1.70450000e+03, 2.31500000e+03, 2.00500000e+03,
       1.49100000e+03, 1.29850000e+03, 4.75000000e+02, 6.13000000e+02,
       8.12500000e+02, 7.05500000e+02, 1.21500000e+03, 1.59250000e+03,
       1.47150000e+03, 1.49200000e+03, 1.76450000e+03, 1.42350000e+03,
       6.23500000e+02, 7.58666667e+02, 2.96666667e+03, 2.26150000e+03,
       8.08000000e+02, 1.16333333e+03, 2.49866667e+03, 2.08500000e+03,
       9.65000000e+02, 1.69200000e+03, 2.02050000e+03, 1.40700000e+03,
       1.11750000e+03, 9.92000000e+02, 1.11450000e+03, 1.59700000e+03,
       1.54950000e+03, 4.39500000e+03, 4.21200000e+03, 3.37700000e+03,
       4.09350000e+03, 1.46400000e+03, 1.56600000e+03, 8.65950000e+03,
       7.79200000e+03, 6.36500000e+02, 1.48250000e+03, 2.20550000e+03,
       2.43900000e+03, 2.07450000e+03, 1.96650000e+03, 2.92800000e+03,
       3.55400000e+03, 2.09400000e+03, 2.67450000e+03, 3.49650000e+03,
       3.28550000e+03, 6.60650000e+03, 5.27000000e+03, 3.42200000e+03,
       3.27200000e+03, 1.34450000e+03, 2.35950000e+03, 2.08800000e+03,
       1.00550000e+03, 2.28450000e+03, 3.16900000e+03, 2.47050000e+03,
       3.40000000e+03, 4.08700000e+03, 3.21900000e+03, 1.72350000e+03,
       1.28000000e+03, 1.68200000e+03, 1.18300000e+03, 1.55650000e+03,
       1.55850000e+03, 1.19583333e+03, 1.73000000e+03, 1.64050000e+03,
       3.38200000e+03, 5.13300000e+03, 2.83400000e+03, 9.52000000e+02,
       2.44750000e+03, 2.35500000e+03, 1.08350000e+03, 1.69100000e+03,
       1.20750000e+03, 4.08700000e+03, 4.07300000e+03, 1.78700000e+03,
       2.40950000e+03, 1.94800000e+03, 1.56600000e+03, 5.96500000e+02,
       1.00800000e+03, 1.85500000e+03, 2.21100000e+03, 3.77900000e+03,
       4.51350000e+03, 3.85600000e+03, 2.27650000e+03, 7.69000000e+02,
       2.40950000e+03, 3.12900000e+03, 4.76600000e+03, 5.72700000e+03,
       7.08300000e+03, 1.00815000e+04, 9.12350000e+03, 7.04900000e+03,
       5.80750000e+03, 6.81300000e+03, 9.51950000e+03, 1.38975000e+04,
       1.60265000e+04, 1.74520000e+04, 2.18270000e+04, 7.84295000e+04,
       1.24543600e+05, 1.27532258e+01, 1.51198413e+01, 5.58504708e+01,
       4.08222222e+01, 2.24949495e+01, 4.44603175e+01, 4.73651961e+01,
       1.23088333e+02, 1.37833333e+02, 1.37982759e+02, 1.31000000e+01,
       1.02000000e+01])

In [9]:
import time
from datetime import datetime

# purpose was to update data each frame 

t2 = datetime.today()
def Update():
    global t2 
    t1 = datetime.now()
    S = client.stock_quotes(symbols=list[0],  
             start=t2, end=t1).df

    d = deque()
    d.append(S)
    

    t2 = t1
    
    
Update()

In [10]:
S_Quotes

                                         bid_price  bid_size bid_exchange  \
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00      54.85     100.0            P
       2026-02-19 00:02:27.101145+00:00      54.85     100.0            P
       2026-02-19 00:02:27.101391+00:00      54.85     100.0            P
       2026-02-19 00:02:28.101014+00:00      54.85     100.0            P
       2026-02-19 00:42:58.499704+00:00      54.07     300.0            Q
...                                            ...       ...          ...
       2026-02-21 00:00:12.882219+00:00      53.50     100.0            P
       2026-02-21 00:31:43.395500+00:00      53.46     100.0            P
       2026-02-21 00:50:08.539961+00:00      53.40     100.0            P
       2026-02-21 00:50:08.594914+00:00      53.30     300.0            P
       2026-02-21 00:53:40.614130+00:00      53.52     100.0            K

                                         ask_price  ask_size ask_exchange  \
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00      55.18     100.0            Q
       2026-02-19 00:02:27.101145+00:00      55.13     100.0            Q
       2026-02-19 00:02:27.101391+00:00      55.18     100.0            Q
       2026-02-19 00:02:28.101014+00:00      55.20     200.0            Q
       2026-02-19 00:42:58.499704+00:00      55.20     200.0            Q
...                                            ...       ...          ...
       2026-02-21 00:00:12.882219+00:00      53.78     100.0            K
       2026-02-21 00:31:43.395500+00:00      53.78     100.0            K
       2026-02-21 00:50:08.539961+00:00      53.78     100.0            K
       2026-02-21 00:50:08.594914+00:00      53.78     100.0            K
       2026-02-21 00:53:40.614130+00:00      53.78     100.0            K

                                        conditions tape
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00        [R]    C
       2026-02-19 00:02:27.101145+00:00        [R]    C
       2026-02-19 00:02:27.101391+00:00        [R]    C
       2026-02-19 00:02:28.101014+00:00        [R]    C
       2026-02-19 00:42:58.499704+00:00        [R]    C
...                                            ...  ...
       2026-02-21 00:00:12.882219+00:00        [R]    C
       2026-02-21 00:31:43.395500+00:00        [R]    C
       2026-02-21 00:50:08.539961+00:00        [R]    C
       2026-02-21 00:50:08.594914+00:00        [R]    C
       2026-02-21 00:53:40.614130+00:00        [R]    C

[43703 rows x 8 columns]

In [11]:
#sum up all recurring size for a specific price: highlights where trades has occured more often 
from cudf import dtype

bid_x_size = pd.DataFrame(S_Quotes).reset_index().groupby('bid_price')['bid_size'].sum()
bid_x_size = bid_x_size.reset_index()

ask_x_size = (
    pd.DataFrame(S_Quotes)
      .reset_index()
      .groupby('ask_price')['ask_size']
      .sum()
      .reset_index()
)

In [12]:
import pyqtgraph as pg 

offset = 0.5  # half a tick, adjust to your market

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)
p1 = win.addPlot(title = "bids")
p1.showGrid(x = True, y = True)
x1 = pg.BarGraphItem(x=bid_x_size.bid_price - offset, 
                     height=bid_x_size.bid_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(255,255,0))
p1.addItem(x1)

p1.setLabel('bottom', 'Price')
p1.setLabel('left', 'Bid Size')

win.nextRow()

p2 = win.addPlot(title = "asks")
p2.showGrid(x = True, y = True)

x2 = pg.BarGraphItem(x=ask_x_size.ask_price, 
                     height=ask_x_size.ask_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(0,255,255))




p2.addItem(x2)
app.exec()

0

In [13]:
class Aggregations:
    def __init__(self, x: pd.DataFrame):
    
        pass 
    # Aggregations

In [14]:
S_Bars['open'].diff()

0         NaN
1     -0.5176
2      0.1676
3      1.0000
4     -0.0500
        ...
828   -0.2899
829    0.0123
830   -0.0377
831    0.1153
832    0.1300
Name: open, Length: 833, dtype: float64

In [15]:
import numpy as np
from collections import deque
import pyqtgraph as pg
from PyQt6 import QtCore

app = pg.mkQApp("RT Scatter")

win = pg.GraphicsLayoutWidget(title="Real-time Scatter")
p = win.addPlot()
p.showGrid(x=True, y=True)

x = np.random.normal(1,3,100)
x2 = np.random.normal(1,3,100)
y = np.random.normal(1,3,100)


l = []
def update():

    print("hello")
  

timer = QtCore.QTimer()
timer.timeout.connect(Update)
timer.start(600)   # ~60 FPS

win.show()
pg.exec()

0

In [16]:
print(type(z))

<class 'str'>