In [5]:
#from pydoc import cli

import numpy as np
#import incoming as inc
import matplotlib.pyplot as plt
import pandas as pd
from alpaca.data.historical import StockHistoricalDataClient, OptionHistoricalDataClient
from alpaca.data.requests import StockBarsRequest, StockQuotesRequest, OptionTradesRequest, OptionBarsRequest, OptionLatestQuoteRequest
OptionBarsRequest
from alpaca.data.enums import DataFeed
from alpaca.trading.enums import ContractType
from alpaca.trading.client import OptionContract, TradingClient, TradeAccount, GetOptionContractsRequest
from alpaca.data.timeframe import TimeFrame ; import cudf as cdf 
from datetime import datetime, timezone, date
import polars as pl
from alpaca.data.live import StockDataStream, OptionDataStream
from account import API_KEY , API_SECRET
from collections import  deque
import pyqtgraph as pg 

global  t2 

# alpaca_data_client.py

class AlpacaDataClient:
    def __init__(self, api_key: str, api_secret: str):
        self.stock_hist = StockHistoricalDataClient(api_key, api_secret)
        self.option_hist = OptionHistoricalDataClient(api_key, api_secret)

        
        self.stock_stream = StockDataStream(api_key, api_secret)
        self.option_stream = OptionDataStream(api_key, api_secret)

    # =========================
    # HISTORICAL — STOCKS
    # =========================
    def stock_bars(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = StockBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_bars(req)

    def stock_trades(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,

            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_trades(req)

    def stock_quotes(self, symbols, start=None, end=None
, limit=None, feed=None):
        req = StockQuotesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.stock_hist.get_stock_quotes(req)

    # =========================
    # HISTORICAL — OPTIONS
    # =========================
    def option_bars(self, symbols, timeframe, start=None, end=None, limit=None, feed=None):
        req = OptionBarsRequest(
            symbol_or_symbols=symbols,
            timeframe=timeframe,
            start=start,
            end=end,
            limit=limit, 
            feed=feed
        )
        return self.option_hist.get_option_bars(req)

    def option_trades(self, symbols, start=None, end=None, limit=None, feed=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed=feed
        )
        return self.option_hist.get_option_trades(req)

    def option_quotes(self, symbols, start=None, end=None, limit=None, feed=None):
        req = OptionTradesRequest(
            symbol_or_symbols=symbols,
            start=start,
            end=end,
            limit=limit,
            feed = feed
        )
        return self.option_hist.get_option_latest_quote(req)
    


    # =========================
    # STREAMING — STOCKS
    # =========================
    def stream_stock_bars(self, symbols, handler):
        self.stock_stream.subscribe_bars(handler, *symbols)

    def stream_stock_trades(self, symbols, handler):
        self.stock_stream.subscribe_trades(handler, *symbols)

    def stream_stock_quotes(self, symbols, handler):
        self.stock_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # STREAMING — OPTIONS
    # =========================
    def stream_option_trades(self, symbols, handler):
        self.option_stream.subscribe_trades(handler, *symbols)

    def stream_option_quotes(self, symbols, handler):
        self.option_stream.subscribe_quotes(handler, *symbols)

    # =========================
    # RUN STREAMS
    # =========================
    async def run_stock_stream(self):
        await self.stock_stream.run()

    async def run_option_stream(self):
        await self.option_stream.run()

TradingClient

In [6]:
class AlcapaTradingClient:
    def __init__(self, api_key: str, api_secret: str):
        self.contracts = TradingClient(
            api_key=api_key,
            secret_key=api_secret,
            paper=True
        )

    def contract(self, underlying_symbols, expiration_date,
                 strike_price_gte, strike_price_lte, type):

        req = GetOptionContractsRequest(
            underlying_symbols=underlying_symbols,  # FIXED
            expiration_date=expiration_date,
            strike_price_gte=strike_price_gte,
            strike_price_lte=strike_price_lte,
            type=type
        )

        return self.contracts.get_option_contracts(req)


tradeClient = AlcapaTradingClient(API_KEY, API_SECRET)

all_contracts = tradeClient.contract(
    underlying_symbols=["AAPL"],
    expiration_date="2026-01-21",
    strike_price_gte="150",
    strike_price_lte="200",
    type=ContractType.CALL
)

In [7]:
all_contracts

{'next_page_token': None, 'option_contracts': []}

ReQuests

In [ ]:


list = ["SYM", "INTC", "NVDA", "ARM", "AMD"]
start_date = datetime(2026,2, 25).date()
end_date = datetime.now()
x = list[0]

def MakeOptionsym(sym:str, type: str, date : datetime, strike):
    date =  date.strftime("%y%m%d")
    strike = int(round(strike * 1000))
    pad = 8 - len(str(strike))
    pad = str(0).zfill(pad)
    lowStrike = 100
    highStrik = 300
    i = sym+str(date)+type+str(pad)+str(strike)
    return i

z = MakeOptionsym(list[1],"C",datetime(2026,1,30), 75)
print(z)
l = "INTC260130C00060000"
start_date

INTC260130C00075000

datetime.date(2026, 2, 25)

In [10]:
client  = AlpacaDataClient(API_KEY, API_SECRET) 
S_Quotes = client.stock_quotes(symbols=x,  start=start_date, end=end_date, feed=DataFeed.SIP).df
S_Bars = client.stock_bars(symbols=x,timeframe=TimeFrame.Minute, start=start_date, end=end_date, feed=DataFeed.SIP).df
S_Trades = client.stock_trades(symbols=x,timeframe=TimeFrame.Minute,start=start_date, end=end_date,feed=DataFeed.SIP).df
# remeber old time and call
#  and new time and add the data frame btw those times

In [23]:
S_Bars = S_Bars.reset_index()
S_Bars

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap
0,SYM,2026-02-25 00:43:00+00:00,56.530,56.530,56.530,56.53,127.0,2.0,56.530000
1,SYM,2026-02-25 00:51:00+00:00,56.490,56.490,56.490,56.49,100.0,1.0,56.490000
2,SYM,2026-02-25 00:52:00+00:00,56.560,56.560,56.560,56.56,150.0,5.0,56.560000
3,SYM,2026-02-25 00:58:00+00:00,56.560,56.560,56.560,56.56,120.0,4.0,56.560000
4,SYM,2026-02-25 10:57:00+00:00,56.750,56.750,56.750,56.75,474.0,3.0,56.750000
...,...,...,...,...,...,...,...,...,...
209,SYM,2026-02-25 17:43:00+00:00,55.500,55.520,55.500,55.51,2066.0,52.0,55.504643
210,SYM,2026-02-25 17:44:00+00:00,55.500,55.520,55.490,55.49,5745.0,88.0,55.507660
211,SYM,2026-02-25 17:45:00+00:00,55.535,55.535,55.500,55.50,819.0,33.0,55.511667
212,SYM,2026-02-25 17:46:00+00:00,55.535,55.540,55.535,55.54,520.0,20.0,55.537917
213,SYM,2026-02-25 17:47:00+00:00,55.520,55.580,55.520,55.52,1561.0,29.0,55.560909

In [21]:


#O_Quotes = client.option_quotes(z, start=start_date, end=datetime.today())
O_Bars = client.option_bars([z,l],timeframe=TimeFrame.Hour,start= start_date, end=datetime.today())
O_Trades = client.option_trades(z, start=start_date, end=datetime.today())

In [92]:
L = 15# odd length
k = np.arange(1, L//2 + 2)          # 1,2,3,4,5,6
kernel = np.r_[k, k[-2::-1]]        # 1,2,3,4,5,6,5,4,3,2,1
kernel = kernel / kernel.sum()

kernel

array([0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125, 0.09375 ,
       0.109375, 0.125   , 0.109375, 0.09375 , 0.078125, 0.0625  ,
       0.046875, 0.03125 , 0.015625])

In [ ]:
y = S_Bars['trade_count']
t = S_Bars['timestamp'].to_numpy().astype("datetime64[ns]").view("int64") / 1e9
v = S_Bars['volume']
dV = np.gradient(v) 
dV = np.convolve(dV, kernel, mode ="same") #Made it smoother with kernel

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)
cumV = np.cumsum(v)                  # integral (total volume so far)
rate = np.gradient(cumV, t)          # volume-per-second (should be >= 0 mostly)

p1 = win.addPlot(title="Cumulative Volume (Integral)")
p1.showGrid(x=True, y=True)
p1.plot( dV, pen=pg.mkPen('y', width=2))
win.nextRow()

#p2 = win.addPlot(title="Rate of Cumulative Volume (dCumV/dt)")
#p2.showGrid(x=True, y=True)
#p2.plot(t, rate, pen=pg.mkPen('c', width=2))

app.exec()

/tmp/ipykernel_64088/1210381774.py:2: UserWarning: no explicit representation of timezones available for np.datetime64
  t = S_Bars['timestamp'].to_numpy().astype("datetime64[ns]").view("int64") / 1e9

0

In [34]:
t

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import time
from datetime import datetime

# purpose was to update data each frame 

t2 = datetime.today()
def Update():
    global t2 
    t1 = datetime.now()
    S = client.stock_quotes(symbols=list[0],  
             start=t2, end=t1).df

    d = deque()
    d.append(S)
    
    t2 = t1
    
    
Update()

In [ ]:

S_Quotes

                                         bid_price  bid_size bid_exchange  \
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00      54.85     100.0            P
       2026-02-19 00:02:27.101145+00:00      54.85     100.0            P
       2026-02-19 00:02:27.101391+00:00      54.85     100.0            P
       2026-02-19 00:02:28.101014+00:00      54.85     100.0            P
       2026-02-19 00:42:58.499704+00:00      54.07     300.0            Q
...                                            ...       ...          ...
       2026-02-21 00:00:12.882219+00:00      53.50     100.0            P
       2026-02-21 00:31:43.395500+00:00      53.46     100.0            P
       2026-02-21 00:50:08.539961+00:00      53.40     100.0            P
       2026-02-21 00:50:08.594914+00:00      53.30     300.0            P
       2026-02-21 00:53:40.614130+00:00      53.52     100.0            K

                                         ask_price  ask_size ask_exchange  \
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00      55.18     100.0            Q
       2026-02-19 00:02:27.101145+00:00      55.13     100.0            Q
       2026-02-19 00:02:27.101391+00:00      55.18     100.0            Q
       2026-02-19 00:02:28.101014+00:00      55.20     200.0            Q
       2026-02-19 00:42:58.499704+00:00      55.20     200.0            Q
...                                            ...       ...          ...
       2026-02-21 00:00:12.882219+00:00      53.78     100.0            K
       2026-02-21 00:31:43.395500+00:00      53.78     100.0            K
       2026-02-21 00:50:08.539961+00:00      53.78     100.0            K
       2026-02-21 00:50:08.594914+00:00      53.78     100.0            K
       2026-02-21 00:53:40.614130+00:00      53.78     100.0            K

                                        conditions tape
symbol timestamp
SYM    2026-02-19 00:02:27.101144+00:00        [R]    C
       2026-02-19 00:02:27.101145+00:00        [R]    C
       2026-02-19 00:02:27.101391+00:00        [R]    C
       2026-02-19 00:02:28.101014+00:00        [R]    C
       2026-02-19 00:42:58.499704+00:00        [R]    C
...                                            ...  ...
       2026-02-21 00:00:12.882219+00:00        [R]    C
       2026-02-21 00:31:43.395500+00:00        [R]    C
       2026-02-21 00:50:08.539961+00:00        [R]    C
       2026-02-21 00:50:08.594914+00:00        [R]    C
       2026-02-21 00:53:40.614130+00:00        [R]    C

[43703 rows x 8 columns]

In [ ]:
#sum up all recurring size for a specific price: highlights where trades has occured more often 
from cudf import dtype

bid_x_size = pd.DataFrame(S_Quotes).reset_index().groupby('bid_price')['bid_size'].sum().reset_index()


filtered = pd.DataFrame(S_Quotes[S_Quotes['bid_size']> 10])

ask_x_size = (
    pd.DataFrame(S_Quotes)
      .reset_index()
      .groupby('ask_price')['ask_size']
      .sum()
      .reset_index()
)

bid_x_size

     bid_price  bid_size
0        52.52    4700.0
1        52.53    1600.0
2        52.54     100.0
3        52.55    8700.0
4        52.56     600.0
..         ...       ...
362      56.20     200.0
363      56.22     100.0
364      56.23     200.0
365      56.24     100.0
366      56.25     100.0

[367 rows x 2 columns]

In [ ]:
import pyqtgraph as pg 

offset = 0.5  # half a tick, adjust to your market

app = pg.mkQApp()
win = pg.GraphicsLayoutWidget(show=True)
p1 = win.addPlot(title = "bids")
p1.showGrid(x = True, y = True)
x1 = pg.BarGraphItem(x=bid_x_size.bid_price - offset, 
                     height=bid_x_size.bid_size, width = 0.09, 
                     size=0.3, brush = pg.mkBrush(255,255,0))
p1.addItem(x1)

p1.setLabel('bottom', 'Price')
p1.setLabel('left', 'Bid Size')

win.nextRow()

p2 = win.addPlot(title = "asks")
p2.showGrid(x = True, y = True)

x2 = pg.BarGraphItem(x=ask_x_size.ask_price - offset, 
                     height=ask_x_size.ask_size , width = 0.09, 
                     size=0.3, brush = pg.mkBrush(0,255,255))


p2.addItem(x2)
app.exec()

0

In [ ]:
class Aggregations:
    def __init__(self, x: pd.DataFrame):
    
        pass 
    # Aggregations

In [ ]:
S_Bars['open'].diff()

0         NaN
1     -0.5176
2      0.1676
3      1.0000
4     -0.0500
        ...
828   -0.2899
829    0.0123
830   -0.0377
831    0.1153
832    0.1300
Name: open, Length: 833, dtype: float64

In [5]:
import numpy as np
from collections import deque
import pyqtgraph as pg
from PyQt6 import QtCore
from realtime import stock_quotes

app = pg.mkQApp("RT Scatter")

win = pg.GraphicsLayoutWidget(title="Real-time Scatter")
p = win.addPlot()
p.showGrid(x=True, y=True)

x = np.random.normal(1,3,100)
x2 = np.random.normal(1,3,100)
y = np.random.normal(1,3,100)


l = []
def update():
    print(len(stock_quotes))

timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(600)   # ~60 FPS

win.show()
pg.exec()

0
0
0
0
0
0
0
0
0
0
0
0
0
0

0

In [ ]:
print(type(z))

<class 'str'>